**Employee Burnout Prediction** 

Import Libraries

In [140]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import date

Reading train and test employee burnout data

In [141]:
df=pd.read_csv("/content/drive/MyDrive/BurnoutData/train.csv")
df_test=pd.read_csv("/content/drive/MyDrive/BurnoutData/test.csv")
df.columns=['emp_id','doj','gender','company_type','wfh','designation','resource_alloc','mental_fatigue_score','burn_rate']
df_test.columns=['emp_id','doj','gender','company_type','wfh','designation','resource_alloc','mental_fatigue_score']
print(df.shape)
df.replace(to_replace='Female',value=1, inplace=True)
df.replace(to_replace='Male',value=-1, inplace=True)

df_test.replace(to_replace='Female',value=1, inplace=True)
df_test.replace(to_replace='Male',value=-1, inplace=True)

df.replace(to_replace='Product',value=1, inplace=True)
df.replace(to_replace='Service',value=-1, inplace=True)

df_test.replace(to_replace='Product',value=1, inplace=True)
df_test.replace(to_replace='Service',value=-1, inplace=True)

df.replace(to_replace='Yes',value=1, inplace=True)
df.replace(to_replace='No',value=-1, inplace=True)

df_test.replace(to_replace='Yes',value=1, inplace=True)
df_test.replace(to_replace='No',value=-1, inplace=True)


df['doj']=pd.to_datetime(df['doj'])
df_test['doj']=pd.to_datetime(df['doj'])
df.head()

(22750, 9)


emp_id        doj  ...  mental_fatigue_score  burn_rate
0  fffe32003000360033003200 2008-09-30  ...                   3.8       0.16
1      fffe3700360033003500 2008-11-30  ...                   5.0       0.36
2  fffe31003300320037003900 2008-03-10  ...                   5.8       0.49
3  fffe32003400380032003900 2008-11-03  ...                   2.6       0.20
4  fffe31003900340031003600 2008-07-24  ...                   6.9       0.52

[5 rows x 9 columns]

In [142]:
print(df['gender'].unique())
print(df['company_type'].unique())
print(df['wfh'].unique())
print(df['designation'].unique())
print(df['resource_alloc'].unique())

print(df_test['gender'].unique())
print(df_test['company_type'].unique())
print(df_test['wfh'].unique())
print(df_test['designation'].unique())
print(df_test['resource_alloc'].unique())

[ 1 -1]
[-1  1]
[-1  1]
[2. 1. 3. 0. 4. 5.]
[ 3.  2. nan  1.  7.  4.  6.  5.  8. 10.  9.]
[ 1 -1]
[-1  1]
[-1  1]
[2. 1. 3. 4. 0. 5.]
[ 5.  2.  3.  6.  4.  7.  1.  9.  8. 10.]


In [143]:
# replacing missing data with mean
print(df['doj'].isnull().values.any())
print(df['gender'].isnull().values.any())
print(df['company_type'].isnull().values.any())
print(df['wfh'].isnull().values.any())
print(df['designation'].isnull().values.any())
print(df['resource_alloc'].isnull().values.any())
print(df['mental_fatigue_score'].isnull().values.any())
print(df['burn_rate'].isnull().values.any())
print(df['resource_alloc'].isnull().sum())
print(df['mental_fatigue_score'].isnull().sum())
print(df['burn_rate'].isnull().sum())

df['resource_alloc'].fillna((df['resource_alloc'].mean()), inplace=True)
df['mental_fatigue_score'].fillna((df['mental_fatigue_score'].mean()), inplace=True)
df['burn_rate'].fillna((df['burn_rate'].mean()), inplace=True)
df_test['resource_alloc'].fillna((df_test['resource_alloc'].mean()), inplace=True)
df_test['mental_fatigue_score'].fillna((df_test['mental_fatigue_score'].mean()), inplace=True)

print(df['resource_alloc'].isnull().sum())
print(df['mental_fatigue_score'].isnull().sum())
print(df['burn_rate'].isnull().sum())

False
False
False
False
False
True
True
True
1381
2117
1124
0
0
0


In [144]:
df.describe()
df.dtypes

emp_id                          object
doj                     datetime64[ns]
gender                           int64
company_type                     int64
wfh                              int64
designation                    float64
resource_alloc                 float64
mental_fatigue_score           float64
burn_rate                      float64
dtype: object

In [145]:
# adding no of months as another feature

df['today_date']=date.today()
df['today_date']=pd.to_datetime(df['today_date'])

df['no_months']=((df.today_date-df.doj)/np.timedelta64(1, 'M'))
df['no_months']=df['no_months'].astype(int)


df_test['today_date']=date.today()
df_test['today_date']=pd.to_datetime(df_test['today_date'])

df_test['no_months']=((df_test.today_date-df_test.doj)/np.timedelta64(1, 'M'))
df_test['no_months']=df_test['no_months'].astype(int)

df.head()

emp_id        doj  gender  ...  burn_rate  today_date  no_months
0  fffe32003000360033003200 2008-09-30       1  ...       0.16  2021-04-18        150
1      fffe3700360033003500 2008-11-30      -1  ...       0.36  2021-04-18        148
2  fffe31003300320037003900 2008-03-10       1  ...       0.49  2021-04-18        157
3  fffe32003400380032003900 2008-11-03      -1  ...       0.20  2021-04-18        149
4  fffe31003900340031003600 2008-07-24       1  ...       0.52  2021-04-18        152

[5 rows x 11 columns]

In [146]:
print(df['no_months'].corr(df['burn_rate']))
print(df['mental_fatigue_score'].corr(df['burn_rate']))
print(df['resource_alloc'].corr(df['burn_rate']))
print(df['no_months'].corr(df['mental_fatigue_score']))
print(df['no_months'].corr(df['resource_alloc']))
print(df['resource_alloc'].corr(df['mental_fatigue_score']))

0.0013215726857202183
0.8782165211163121
0.811061911631428
-0.0026650077667925414
0.00044109437741534664
0.7392679608532605


In [147]:
X=df[['no_months','gender','company_type','wfh','designation','resource_alloc','mental_fatigue_score']]
y=df[['burn_rate']]
df_test=df_test[['no_months','gender','company_type','wfh','designation','resource_alloc','mental_fatigue_score']]

Random Forest Regressor

In [148]:
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.25)

In [149]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
rf_model=RandomForestRegressor()
y_train_list = y_train['burn_rate'].to_list()

# Grid search to find optimal parameters
from sklearn.model_selection import GridSearchCV
param_grid = {
    'bootstrap': [True],
    'max_depth': [20, 30, 40],
    'min_samples_split': [10,20],
    'n_estimators': [100, 200, 300]
}

rf_gscv = GridSearchCV(rf_model, param_grid, cv=5)
rf_gscv.fit(X_train, y_train_list)

GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestRegressor(bootstrap=True, ccp_alpha=0.0,
                                             criterion='mse', max_depth=None,
                                             max_features='auto',
                                             max_leaf_nodes=None,
                                             max_samples=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators=100, n_jobs=None,
                                             oob_score=False, random_state=None,
                                             verbose=0, warm_start=False),
             iid='deprecated', n_jo

In [150]:
# best parameters
print('Best parameters ',rf_gscv.best_params_)
print('\nThe score for the best parameters = ',rf_gscv.best_score_)

Best parameters  {'bootstrap': True, 'max_depth': 40, 'min_samples_split': 20, 'n_estimators': 200}

The score for the best parameters =  0.8606755996714464


In [154]:
# fitting optimal model and calculating MSE for validation set
rf_model = RandomForestRegressor(bootstrap=True, max_depth=40, min_samples_split=20, n_estimators=200)
rf_model.fit(X_train,y_train.values.ravel())

rf_pred = rf_model.predict(X_valid)
y_true = y_valid['burn_rate'].to_list()
print(rf_pred)

[0.70848856 0.41092996 0.65204785 ... 0.50589839 0.40073607 0.35736206]


In [155]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_true, rf_pred))

0.005387605731067602


In [156]:
# predicting burn out rate for test data
df_test=df[['no_months','gender','company_type','wfh','designation','resource_alloc','mental_fatigue_score']]
rf_pred = rf_model.predict(df_test)
print(rf_pred)

[0.25740921 0.33599058 0.42053618 ... 0.67447148 0.47967786 0.61956207]
